### ISSUE TITLE
[Bug]: Prometheus integration doesn't work

### ISSUE THREAD

**Issue by marlester-dev** [terrarium-earth/Cadmus#64]
### Bug Description

I downloaded Prometheus v1.2.5 and Cadmus v1.0.8.
I typed in "/roles open"
I created a new role with 9999 max chunk claims
I gave myself the role with "/member nick addrole 317bd691-2fd9-4aa8-b0db-d8284256d7ed"
I opened the claim map. I still had 1089 max claims

### How to Reproduce?

Download Prometheus v1.2.5 and Cadmus v1.0.8.
Type in "/roles open"
Create a new role with 9999 max chunk claims
Give yourself the role with "/member nick addrole roleid"
Open the claim map. It still has 1089 max claims

### Expected Behavior

I have 9999 max chunks in claim map

### Version

v1.0.8

### Mod Loader Version

1.20.1 - 0.16.9

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by marlester-dev** [comment]
my mods: https://pastebin.com/wjA9it6w

**Comment by marlester-dev** [comment]
on a dedicated server

**Comment by marlester-dev** [comment]
[17:10:27] [Server thread/ERROR]: Error loading saved data: scoreboard
java.lang.NullPointerException: Cannot read the array length because the return value of "com.mojang.authlib.yggdrasil.response.ProfileSearchResultsResponse.getProfiles()" is null
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:58) ~[authlib-4.0.43.jar:?]
	at net.minecraft.class_3312.method_14509(class_3312.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_3312.method_14515(class_3312.java:150) ~[server-intermediary.jar:?]
	at earth.terrarium.cadmus.common.teams.VanillaTeamProvider.lambda$getTeamMembers$0(VanillaTeamProvider.java:30) ~[cadmus-fabric-1.20.1-1.0.8.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at earth.terrarium.cadmus.common.teams.VanillaTeamProvider.getTeamMembers(VanillaTeamProvider.java:30) ~[cadmus-fabric-1.20.1-1.0.8.jar:?]
	at earth.terrarium.cadmus.common.teams.TeamHelper.getTeamMembers(TeamHelper.java:34) ~[cadmus-fabric-1.20.1-1.0.8.jar:?]
	at earth.terrarium.cadmus.common.compat.prometheus.PrometheusMaxClaimProvider.calculate(PrometheusMaxClaimProvider.java:20) ~[cadmus-fabric-1.20.1-1.0.8.jar:?]
	at earth.terrarium.cadmus.api.teams.TeamProvider.onTeamChanged(TeamProvider.java:145) ~[cadmus-fabric-1.20.1-1.0.8.jar:?]
	at earth.terrarium.cadmus.common.teams.VanillaTeamProvider.onTeamChanged(VanillaTeamProvider.java:97) ~[cadmus-fabric-1.20.1-1.0.8.jar:?]
	at net.minecraft.class_2995.handler$cem000$cadmus$addPlayerToTeam(class_2995.java:526) ~[server-intermediary.jar:?]
	at net.minecraft.class_2995.method_1172(class_2995.java:89) ~[server-intermediary.jar:?]
	at net.minecraft.class_273.method_1215(class_273.java:93) ~[server-intermediary.jar:?]
	at net.minecraft.class_273.method_1219(class_273.java:87) ~[server-intermediary.jar:?]
	at net.minecraft.class_273.method_32481(class_273.java:32) ~[server-intermediary.jar:?]
	at net.minecraft.class_2995.method_32704(class_2995.java:242) ~[server-intermediary.jar:?]
	at net.minecraft.class_26.method_120(class_26.java:71) ~[server-intermediary.jar:?]
	at net.minecraft.class_26.method_20786(class_26.java:58) ~[server-intermediary.jar:?]
	at net.minecraft.class_26.method_17924(class_26.java:42) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_17976(MinecraftServer.java:308) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:362) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:324) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:169) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:646) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by marlester-dev** [comment]
seems like the teams are corrupt

**Comment by marlester-dev** [comment]
seems like some of my mods are modifying standard teams so that cadmus throws an error

**Comment by marlester-dev** [comment]
installed agronauts and deleted cadmus data file but didnt work
